#单点eureka
server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1


# =====================================================================================


#单点eureka
#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://127.0.0.1:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1

# =====================================================================================



#集群eureka服务端相互注册（eurekaServer1中的defaultZone中的DEFAULT_URL为eurekaServer2和eurekaServer3的地址）

#eurekaServer1

#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://192.168.10.2:8762/eureka/,http://192.168.10.3:8763/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.10.1
#    #默认心跳周期（30秒注册一次）
#    lease-renewal-interval-in-seconds: 30
#    #最小过期时长(90没有进行心跳, 将不再进行心跳注册,认为服务失效-宕机)
#    lease-expiration-duration-in-seconds: 90
#  server:
#    #(服务失效-宕机60秒将服务剔除服务列表)
#    eviction-interval-timer-in-ms: 60000

# -------------------------------------------------------------------------------------


#eurekaServer2

#server:
#  port: 8762
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://192.168.10.1:8761/eureka/,http://192.168.10.3:8763/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.10.2
#    #默认心跳周期（30秒注册一次）
#    lease-renewal-interval-in-seconds: 30
#    #最小过期时长(90没有进行心跳, 将不再进行心跳注册,认为服务失效-宕机)
#    lease-expiration-duration-in-seconds: 90
#  server:
#    #(服务失效-宕机60秒将服务剔除服务列表)
#    eviction-interval-timer-in-ms: 60000

# -------------------------------------------------------------------------------------


#eurekaServer3

#server:
#  port: 8763
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://192.168.10.1:8761/eureka/,http://192.168.10.2:8762/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.10.3
#    #默认心跳周期（30秒注册一次）
#    lease-renewal-interval-in-seconds: 30
#    #最小过期时长(90没有进行心跳, 将不再进行心跳注册,认为服务失效-宕机)
#    lease-expiration-duration-in-seconds: 90
#  server:
#    #(服务失效-宕机60秒将服务剔除服务列表)
#    eviction-interval-timer-in-ms: 60000

# ======================================================================================


#user客户端(注册所有的eureka服务)

#user-service
#server:
#  port: 8080
#spring:
#  application:
#    name: user-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://192.168.10.4:8761/eureka/,http://192.168.10.5:8762/eureka/,http://192.168.10.3:8763/eureka/


#consumer客户端(注册所有的eureka服务)

#consumer-service
#server:
#  port: 8081
#spring:
#  application:
#    name: consumer-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://192.168.10.4:8761/eureka/,http://192.168.10.5:8762/eureka/,http://192.168.10.3:8763/eureka/
#user-service :
#  ribbon :
#      #设置ribbon 对user-service服务进行负载均衡的方式为随机
#      NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule