#单点eureka
server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1


# =====================================================================================



#多个eureka服务端相互注册（eurekaServer1中的defaultZone中的DEFAULT_URL为eurekaServer2和eurekaServer3的地址）

#eurekaServer1

#server:
#  port: 8761
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://192.168.10.2:8762/eureka/,http://192.168.10.3:8763/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.10.1


# -------------------------------------------------------------------------------------


#eurekaServer2

#server:
#  port: 8762
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://192.168.10.1:8761/eureka/,http://192.168.10.3:8763/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.10.2


# -------------------------------------------------------------------------------------


#eurekaServer3

#server:
#  port: 8763
#spring:
#  application:
#    name: eureka-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://192.168.10.1:8761/eureka/,http://192.168.10.2:8762/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.10.3


# ======================================================================================


#user客户端(注册所有的eureka服务)

#user-service
#server:
#  port: 8080
#spring:
#  application:
#    name: user-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://192.168.10.4:8761/eureka/,http://192.168.10.5:8762/eureka/,http://192.168.10.3:8763/eureka/


#consumer客户端(注册所有的eureka服务)

#consumer-service
#server:
#  port: 8081
#spring:
#  application:
#    name: consumer-server
#eureka:
#  client:
#    service-url:
#      defaultZone : http://192.168.10.4:8761/eureka/,http://192.168.10.5:8762/eureka/,http://192.168.10.3:8763/eureka/
